name: Flask CI  # Bu workflow'un GitHub'daki görünen adı

on:
  push:         # Ne zaman çalışacak?
    branches: [ main ]  # main branch'e push olunca
  pull_request:
    branches: [ main ]  # PR oluşturulunca da çalışır

jobs:
  build:        # Job adı

    runs-on: ubuntu-latest  # GitHub'un verdiği sanal makine (Ubuntu)

    steps:
    - name: Reposuyu klonla
      uses: actions/checkout@v3  # Kodları indirir

    - name: Python ortamını hazırla
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Hangi Python versiyonu yüklensin?

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Flask uygulamasını başlatmayı dene
      run: |
        python app.py &     # Arka planda başlat
        sleep 5             # 5 saniye bekle (başlaması için)
        echo "✅ Flask uygulaması çalıştırıldı!"

