name: Flask Visitor Book CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run app
      run: |
        export FLASK_APP=app.py
        flask run &
        sleep 5
        curl http://127.0.0.1:5000/

